apiVersion: 1

providers:
  - name: 'Flask Dashboards'
    orgId: 1
    folder: 'Flask'
    type: file
    disableDeletion: false
    editable: true
    updateIntervalSeconds: 1
    allowUiUpdates: true
    options:
      path: /var/lib/grafana/dashboards/flask
