apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: grafana
  name: grafana-cm0
data:
  datasources.yaml: |
    apiVersion: 1

    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus:9090
        isDefault: true
