apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: grafana
  name: grafana-cm1
data:
  default.yaml: |
    apiVersion: 1
    providers:
      - name: 'Flask Dashboards'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        updateIntervalSeconds: 1
        allowUiUpdates: true
        options:
          path: /var/lib/grafana/dashboards